name: Build, Release, and Send APK via Email

on:
  push:
    branches:
      - develop

jobs:
  build-release-and-send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

    - name: Run flutter doctor
      run: flutter doctor

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
        name: 'Release v1.0.${{ github.run_number }}'
        body: |
          Automated release for commit ${{ github.sha }}.
        draft: false
        prerelease: false

    - name: Send Email with APK Download Link
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: "smtp.gmail.com"
        server_port: 465
        username: "wanenyosra@gmail.com"  
        password: "${{ secrets.EMAIL_PASSWORD }}" 
        subject: "New APK Build Available"
        body: "The new APK build is available for download at: https://github.com/${{ github.repository }}/releases/download/v1.0.${{ github.run_number }}/app-release.apk"
        to: "yosra.wanen@e-iagen.com"  
        from: "yosrawanene28@gmail.com"  
        secure: true 